### ISSUE TITLE
zeros padding in Map3D

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/solarbextrapolation#6]
What is the reason behind having a padding of 2 zeros at +/- (x,y,z) when constructing the 3D volume that holds the extrapolated magnetic field?

The relevant code starts at [Line 112 in `extrapolators/potential_field_extrapolator.py`](https://github.com/sunpy/solarbextrapolation/blob/master/solarbextrapolation/extrapolators/potential_field_extrapolator.py#L112).

**Comment by Alex-Ian-Hamilton** [comment]
In [Line 111](https://github.com/sunpy/solarbextrapolation/blob/master/solarbextrapolation/extrapolators/potential_field_extrapolator.py#L111) I try to explain.
Essentially, because we're using 2nd order numerical differentiation (essentially div(phi)) each cell needs data from the cells either side, this means that the cells on the edge done have the necessary data (potential field on either side) to complete the differentiation.
So they are ghost cells in the output, with no vector field component.
I was tempted to add a first order differentiation to calculate the cells one in from the edge, but I never got round to that.

**Comment by wtbarnes** [comment]
Ah I see. In retrospect, this should have been more obvious to me, especially given the comment that you pointed out.

So in the post-processing/visualization phase, this "zero padding" can be trimmed off, correct?

**Comment by Alex-Ian-Hamilton** [comment]
No worries, TBH I try to add comments to describe, but it's hard to tell if it makes sense to someone who didn't code it until someone queries.

You wouldn't want to trim it, it's still part of the volume you're calculating the field for, it's just the potential extrapolator (with requires numerical differentiation) can't get the values for that very outer edge.
If you trim you will be effectively stretching the resulting field out a bit.
For visualization, MayaVi simply doesn't plot anything with zero vectors, so this region is ignored.
For analysis you'll want to ignore this region also.

**Comment by wtbarnes** [comment]
Hmm...ok. In the docstring for `_determine_vec`, you say that the x and y dimensions of the 3D volume are the same as those of the boundary magnetogram. So does this mean that features near the edge of the magnetogram get "lost" in the zero padding?

**Comment by Alex-Ian-Hamilton** [comment]
Yes. For the potential extrapolator that will be the case.

**Comment by wtbarnes** [comment]
Another thought:

Since the zeros padding is just for the numerical differentiation and doesn't constitute anything physical, couldn't the volume be expanded by 2 in each direction?

That way in the end, the padding can just be trimmed and your "non-zero" volume has the same x and y dimensions as your boundary map. Doing it this way, it doesn't seem like you'd be stretching the field since the trimmings don't constitute physical space.

Just a thought. Perhaps I'm not taking some detail into consideration.

**Comment by Alex-Ian-Hamilton** [comment]
Well it's because although you can calculate the potential field (Phi) throughout the volume, converting that potential to a vector field requires the numerical differentiation step, and that is necessarily going to leave a layer of ghost cells round the edge that is as deep as the order of the differentiation used.
It is physical in the sense that the potential field is well defined within the volume and it's just converting that to a vector field is not easily done without leaving those ghost cells.

Expanding by 2 in the x and y should be do-able, but would require additional boundary data.
Expanding in the z direction would be trivial at the top of the volume, but not possible on the very bottom surface.

Part of the reason for leaving it like that was because the API is designed to be expanded with other extrapolators and this is a problem unique to the Potential Extrapolator.
If you really want that total volume then I could modify the differentiation routine to use a 1st order technique on the cells one in from the edge and approximate the very edge cells. Potentially using an optional input to allow user control.
